### PR TITLE
Added a tag helper for bootstrap panel. #45

### PR DESCRIPTION
**Pull request by manojkulkarni30**
Added a new tag helper for bootstrap panel. Added five new files in TagHelperSamples.Bootstrap project. Please review. #45

### CODE REVIEW

**Comment by manojkulkarni30** [comment]
@dpaquette please let me know if you have any suggestions.

**Comment by dpaquette** [comment]
@manojkulkarni30 thanks for reminding me about this. This tag helper looks great. I think one thing that would simplify usage of the tag helper is if we made the Panel Type an Enum instead of a string.  This would people intellisense support so they know what types are valid. 

Let me know if you want to make that change as part of this PR. If not I am happy to merge this now an we can tackle that as a separate issue.

**Comment by manojkulkarni30** [comment]
@dpaquette yes sure i will make that change and will submit it as a part of this PR. Thank you for your suggestion.

**Comment by manojkulkarni30** [comment]
Panel type field is updated from string to enum and updated the PR. @dpaquette Please review. Once again thank you for the suggestion. It really simplified the usage of tag helper.

**Comment by dpaquette** [comment]
This is great! Thanks so much for the contribution

**Pull request merged**
